### ISSUE TITLE
webauthn-authenticator-rs: aaguid extension is missing from x509 certificate

### ISSUE THREAD

**Issue by stephenjudkins** [kanidm/webauthn-rs#330] opened 2023-07-12 16:22 UTC
### I did this
I attempted to use this library as a token implementation to interact with our server in a test context.

### I expected the following
I expected the server to interoperate with this software token and accept the registration credentials. The spec requires that token implementations include extension OID 1.3.6.1.4.1.45724.1.1.4 (id-fido-gen-ce-aaguid) in x509 client certificate.

### What actually happened
I saw the error `Certificate aaguid extension is missing` (from  this code path:
https://github.com/tweag/webauthn/blob/f0d8046fe85d9165d2dd6b4325319f99b548b022/src/Crypto/WebAuthn/AttestationStatementFormat/Packed.hs#L117). As far as I can tell this code does not include the above extension.

### Version (and git commit)
a7bb46177c23a9afe078658ffacf34cc8aaa30fe

**Comment by Firstyear** [comment] 2023-07-13 04:05
Per the specification: https://w3c.github.io/webauthn/#sctn-packed-attestation-cert-requirements

```
If the related attestation root certificate is used for multiple authenticator models, the Extension OID 1.3.6.1.4.1.45724.1.1.4 (id-fido-gen-ce-aaguid) MUST be present, containing the AAGUID as a 16-byte OCTET STRING. The extension MUST NOT be marked as critical.
```

In otherwords this extension is *optional* and only required if the attestation cert is used for multiple models to allow distinction of them by the certificate. Since the softtoken is a singular model and doesn't sign multiple different types of authenticators it is valid for this extension to be missing. 

We *did* consider adding this, but it's complicated by the api that openssl presents: https://docs.rs/openssl/latest/openssl/x509/struct.X509Extension.html#method.new_from_der

**Comment by stephenjudkins** [comment] 2023-07-13 16:17
Thank you for the context here, I appreciate it!

I do wonder how many other relying party implementations do require this extension. I'm going to file a bug with the one we use.

**Comment by Firstyear** [comment] 2023-07-17 02:09
From our experience, given the flaws we have hit in attestation and the fido mds, we believe that very few RP's or RP libraries actually support attestation in meaningful ways. You're probably the second that I have ever seen that supports it. 

Closing this now since it's not a bug, but feel free to continue the conversation if you wish :)

**Closed by Firstyear** 2023-07-17 02:09 UTC
