### ISSUE TITLE
Support for Nitrokey FIDO2 + Ubuntu + Firefox

### ISSUE THREAD

**Issue by TheBolliwood** [kanidm/webauthn-rs#32] opened 2020-09-26 08:28 UTC
Hi! Really nice library. I'd like to support WebAuthn in some of my projects.
Sadly the example currently doesn't work.

I have the [Nitrokey FIDO2](https://www.nitrokey.com/files/doc/Nitrokey_FIDO2_factsheet.pdf), Ubuntu 20.04 LTS and Firefox 80.

After clicking "Register" my key doesn't show me its indication that I should touch it. This works as expected with my key/browser combination on https://webauthn.io/.
The console shows no errors.

Let me know how I can help you!

**Comment by Firstyear** [comment] 2020-09-27 23:56
Hi there,

Sorry for the late response, I'm glad you like the library.

I'm surprised that this key does not work as it should be supported. But regardless, to get the details needed so I can debug this can you re-run the example server with `cargo run --example actix -- -d` and then you can email me the full output to william at blackhats.net.au please!

**Comment by TheBolliwood** [comment] 2020-09-28 09:49
Thanks for the reply.
I hope you got my mail.

**Comment by Firstyear** [comment] 2020-11-21 05:34
Hi @TheBolliwood. I have finally recieved my NitroKey and I can reproduce this issue. It is a duplicate of #34, which is a combination of two things. First Firefox only supports CTAP1 which is unable to do userverification to U2F devices. Second it is a mistake in the example from my own testing where I left UV::Required in the settings.

I will be uploading a new version soon which corrects this issue and has improved handling of UserVerification related to issues I have found with webauthn. But for now, if you want to re-check this you can change examples/actix/actors.rs, UserVerificationPolicy::Discouraged. 

Thanks for your patience.

**Closed by Firstyear** 2020-11-21 05:34 UTC
