### ISSUE TITLE
Authenticator that enforce user verification on registration but no on authentication

### ISSUE THREAD

**Issue by sorz** [kanidm/webauthn-rs#91] opened 2022-01-11 09:12 UTC
From docs of `WebauthnConfig::get_require_uv_consistency()`:
> This applies to certain classes of authenticators that if registered with userVerification::Discouraged, will still perform and enforce that userVerification is true.
> For these authenticators, since they **always enforce userVerification**, we can use this as an extra security check, and continue to enforce that they provide user verification in all subsequent authentication operations. [emphasis added]

This seems not be true in my case.
I use Windows 11 with Canokey. When registering with UV::Discouraged, the PIN is required and UV=true. While in authentication, UV=false and only a touch is required, for the same authenticator.

This caused that I can register without issue, but fail to log in later due to UV consistency checking, under the default settings of webauthn-rs.

I don't know if that behavior of authenticator is common, or only my system acting like this?

**Comment by Firstyear** [comment] 2022-01-12 01:58
Hi there,

Thanks for reporting this. I believe that this is a bug in the canokey. I have reported it here https://github.com/canokeys/canokey-core/issues/42 

When you send a discouraged to the authenticator, and it still requests a pin or verification this establishes to the user that "this credential will always require verification". The fact that subsequent attempts with discouraged then do NOT request verification breaks this association, and causes the same issues as UV preferred.

As a result I have looked at the canokey source, and it appears in the ctap applet they have different logic, which is why I have raised the bug with them. Feel free to check that out for more details :) 

PS: I'm currently reworking the webauthn-rs demo site, and plan to host it online with a key-compat tester and reporting tool, so once that's up I'd appreciate if you want to give it a test.  :)

**Comment by dangfan** [comment] 2022-01-12 02:21
Hi there,

I've checked [the documentation of CTAP 2.0](https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#authenticatorMakeCredential). Step 6 in Section 5.1 (authenticatorMakeCredential) states that "If pinAuth parameter is not present and clientPin been set on the authenticator, return CTAP2_ERR_PIN_REQUIRED error."

While in Section 5.2, there is no such requirement.

Therefore, the inconsistency is correct according to the spec.

**Comment by Firstyear** [comment] 2022-01-12 02:25
@dangfan That may mean it's a bug in the specification then. It appears that the ctap2 protocol specification issue tracker is not publicly available so I'll have to follow up with that. 

At the very least, I still consider it an issue in canokey as it creates a mismatch of expectations to the user when they a registering an authenticator. If a pin is requested at registration, then it must also be requested during authentication.

**Comment by Firstyear** [comment] 2022-01-14 04:44
@sorz I'm talking to someone from FIDO about this. It appears it's "kind-of" fixed in CTAP2.1, but I'm still not sure how to approach this for CTAP2.0. 

If a credential is registered with UV=true when discouraged, then for the user, they believe that the credential they have enrolled, now will require that pin. Breaking this association is something I'm extremely hesitant to do as it has real security consequences for people since the act of entering a PIN is now inconsistent and meaningless, since it will never be enforced so then required to discouraged downgrade attacks are possible. 

As far as I can see the api we have in webauthn-rs however does defend from this. If you are using `generate_challenge_authenticate_options` or `generate_challenge_authenticate` then we'll handle this correctly for your credentials.

So at this time, while it's annoying and interesting that you found this, I can see why @dangfan may want to remain "ctap2.0 compliant" as their motivations are different. Webauthn-rs however is *not* interested in standards compliance - we are interested in developing a secure authentication library that communicates within boundaries of webauthn.

So I think in this case it's "not a bug" since our apis correctly recognise that if you registered with discouraged and provide a UV=true in response, then our API's will enforce that you MUST provide UV=true by setting required in all future contexts.

The only time you can "get around this" is if you are using `generate_challenge_authenticate_credential` which allows you to side step this behaviour and set discouraged. 

Either way, I will continue to discuss this with the contact I have at fido so that we can hopefully improve the standard.

**Comment by Firstyear** [comment] 2022-01-15 10:06
@sorz Actually, I just found a possible edge case that could be causing your issue, I'm re-opening.

**Comment by Firstyear** [comment] 2022-01-29 06:15
@sorz Can you please follow the steps on https://webauthn.firstyear.id.au/compat_test and if an error occurs, follow the steps to submit the report? I'm likely to make a number of changes to some parts of the library to resolve this issue that you are experiencing

**Comment by Firstyear** [comment] 2022-02-01 03:17
Will be resolved by https://github.com/kanidm/webauthn-rs/pull/94

**Closed by Firstyear** 2022-02-01 03:17 UTC
