### ISSUE TITLE
X509PublicKey cose algorithm parameter

### ISSUE THREAD

**Issue by madwizard-thomas** [kanidm/webauthn-rs#90] opened 2021-12-04 09:32 UTC
X509PublicKey takes a public key (actually this struct is a X509 certificate, not just the public key) but also a COSE algorithm identifier. However, X509 certificates already contain a signature algorithm themselves, so the COSE algorithm is redundant and leaves room for inconsistencies. 

The algorithm does needs to match the COSE algorithm in some cases, for example in the attestation certificate but that can be done by converting pubk.signature_algorithm() to a COSE algorithm and comparing it.

There are already a few places in the code where this algorithm causes confusion:
[crypto.rs](https://github.com/kanidm/webauthn-rs/blob/43905f91b01e14d643f200232229ea874f1d832d/src/crypto.rs#L250), the algorithm follows from the certificate, it is redundant
```rust
pubk: x509::X509::from_pem(APPLE_X509_PEM).unwrap(),
// This content type was obtained statically (this certificate is static data)
t: COSEAlgorithm::ES384,
```

[attestation.rs](https://github.com/kanidm/webauthn-rs/blob/43905f91b01e14d643f200232229ea874f1d832d/src/attestation.rs#L599), it might very well not be right, the certificates are supplied by the device
```rust
// FIXME: this is determined empirically, not sure if it's always right.
std::iter::once(alg).chain(std::iter::repeat(COSEAlgorithm::ES384)),
```
	
[attestation.rs](https://github.com/kanidm/webauthn-rs/blob/43905f91b01e14d643f200232229ea874f1d832d/src/attestation.rs#L92), same algorithm used for all certificates in the chain, they do not have to use the same algorithm
```rust
.and_then(|b| crypto::X509PublicKey::try_from((b.as_slice(), alg)))
```

I would suggest removing `t` from the X509 struct and replacing it by a method that returns the COSE algorithm identifier based on the X509 signature algorithm. Or determining it on creation and caching it in a member variable.

**Comment by Firstyear** [comment] 2021-12-05 22:44
The issue is the RSA types. There is no way to tell from the x509 which of these variants we want to use: https://github.com/kanidm/webauthn-rs/blob/43905f91b01e14d643f200232229ea874f1d832d/src/proto.rs#L168

**Comment by madwizard-thomas** [comment] 2021-12-06 09:39
I thought that there were different algorithm identifiers for the variants (e.g. `sha256WithRSAEncryption`), but reading the spec again, I see this is only the case for the issuer's signature algorithm in the certificate.

In that case I think the algorithm still doesn't belong in the struct, since it does not follow from the certificate it represents. The cose algorithm is a combination of key type/length and a digest (hashing) method. The first follows from the certificate, the second is dependent on the context. Openssl requires the hashing function as a parameter as well when signing/verifying, I think it should be a parameter of verify_signature too (e.g sha256/512 etc.). The algorithm is already available to the caller in all cases.

The only other use is in try_from (x509->cose key). I would try to eliminate conversions from x509 to cose keys if possible, or replace it with a conversion to COSEKeyType which does not need the algorithm. As far as I can tell the only current use is to compare the keys in `verify_apple_anonymous_attestation`, this can be done by comparing the key information only (e.g COSEKeyType <-> x509 subject public key).

**Comment by Firstyear** [comment] 2021-12-06 22:02
Honestly I think this is an argument over semantics. We *require* the x509 cert paired with what COSE alg it's using so we can persist that pair of data, to then do future operations. We can't not seperate these. There is no way to seperate them. 

If anything the confusion is a naming one. We could rename X509PublicKey to CosePublicKey and move on IMO.

**Comment by madwizard-thomas** [comment] 2021-12-08 15:00
It may be semantics, I think as X509 and COSE as separate domains but I can see your point. Still, the pairing only applies to the attestation certificate, not the other certificates in the chain so [using the same alg for all](https://github.com/kanidm/webauthn-rs/blob/43905f91b01e14d643f200232229ea874f1d832d/src/attestation.rs#L92) is still an assumption that may be wrong. The certificates in the chain can even use a different key type (e.g EC attestation certificate signed by an RSA certificate).

**Comment by Firstyear** [comment] 2021-12-08 21:04
@madwizard-thomas The first cert in the chain is the attestation cert, and then we use the x509 cert combined with that alg to verify this here https://github.com/kanidm/webauthn-rs/blob/43905f91b01e14d643f200232229ea874f1d832d/src/attestation.rs#L105 

It's worth noting that at that point of the process, alg is purely related to the alg of the attestation cert in use and how it created the signature, it is *not* related to the public key type and it's algorithm, which is determined https://github.com/kanidm/webauthn-rs/blob/43905f91b01e14d643f200232229ea874f1d832d/src/attestation.rs#L77 via https://github.com/kanidm/webauthn-rs/blob/43905f91b01e14d643f200232229ea874f1d832d/src/crypto.rs#L291 so there is no assumption being made here about the algorithms in use.

**Comment by madwizard-thomas** [comment] 2021-12-09 09:01
> @madwizard-thomas The first cert in the chain is the attestation cert, and then we use the x509 cert combined with that alg to verify this here

That does work for `arr_x509[0]` but for `arr_x509[1..]` the alg is not really related to the certificates.

**Comment by Firstyear** [comment] 2021-12-09 21:56
Yes, we could clean up that section potentially, since we can just feed alg to the verify section. I think the reason I did it like this was so that I didn't duplicate the verify code, but I can see how this could be refactored pretty easily too.

**Comment by Firstyear** [comment] 2022-03-03 00:59
Fixed in https://github.com/kanidm/webauthn-rs/pull/100

**Closed** 2022-03-03 01:00 UTC
