### ISSUE TITLE
Firefox 98 + Windows 11 + Windows Hello truncates aaguid

### ISSUE THREAD

**Issue by ericmarkmartin** [kanidm/webauthn-rs#105] opened 2022-03-12 18:10 UTC
As we discussed, I updated to windows 11 and ran the compat test to try to collect a tpm vector. I still need to analyze the vectors to see what format we're using but was surprised by the number of failures

Please add any extra details here:

* Browser version: Firefox 98.0
* Type of authenticator hardware: Windows hello. My processor is a Ryzen 9 which I believe has a TPM module. I authenticated using my pin.
* Any other details that may help

```
{
  "direct_attest_1": {
    "Passed": {
      "rs": {
        "cred_id": "EzjDD8m1NnXx7CPfRjQJrh_lFX4fIKTTCPX-2X6ZSYc",
        "uv": true,
        "alg": "RS256"
      },
      "ccr": {
        "publicKey": {
          "rp": {
            "name": "webauthn.firstyear.id.au",
            "id": "webauthn.firstyear.id.au"
          },
          "user": {
            "id": "Y29tcGF0dXNlcg",
            "name": "compatuser",
            "displayName": "compatuser"
          },
          "challenge": "BjAqz29Ec_vJtUolavnSAGAgJcaUwTIVrKH16LXcYAU",
          "pubKeyCredParams": [
            {
              "type": "public-key",
              "alg": -7
            },
            {
              "type": "public-key",
              "alg": -35
            },
            {
              "type": "public-key",
              "alg": -36
            },
            {
              "type": "public-key",
              "alg": -257
            },
            {
              "type": "public-key",
              "alg": -258
            },
            {
              "type": "public-key",
              "alg": -259
            },
            {
              "type": "public-key",
              "alg": -37
            },
            {
              "type": "public-key",
              "alg": -38
            },
            {
              "type": "public-key",
              "alg": -39
            },
            {
              "type": "public-key",
              "alg": -8
            },
            {
              "type": "public-key",
              "alg": -65535
            }
          ],
          "timeout": 60000,
          "attestation": "direct",
          "authenticatorSelection": {
            "requireResidentKey": false,
            "userVerification": "discouraged"
          }
        }
      },
      "rpkc": {
        "id": "EzjDD8m1NnXx7CPfRjQJrh_lFX4fIKTTCPX-2X6ZSYc",
        "rawId": "EzjDD8m1NnXx7CPfRjQJrh_lFX4fIKTTCPX-2X6ZSYc",
        "response": {
          "attestationObject": "o2NmbXRmcGFja2VkZ2F0dFN0bXSiY2FsZzkBAGNzaWdZAQCjBbdY-Q0qXTabiieICTaU0765ide6hPvIxPZV3xjuegHJku-bUy_J8nZRGWwXOI3dSbv-LUp2Ft9joRwk8lFxHYSiQ0GLonmJbb2cOxxp5URWsOX6qIlbFS2tFGPx8XZI0xuBd2LBXzQn34mELIgeF6Qsjh-j2lbGsFxOR7SImklUbyfTiJtoeAG1s9U8SDEXipsN-AGZUa7tietzs-VJl1q1Foee2zVUchA42NsguK57eoDvdic6ckTl9HQ8aKxdVjA2zq4J-ugX9LTD6vbDFEGu-3B4-SXJx916VSnTeFIkPWHlK2ZbyciZ0z2K_jX4EboYmBKFCJ54YbeQmVwDaGF1dGhEYXRhWQFnarm78N-aFvkduzO7sTL6-dF8eCxIJsbscOzuWNl-9SpFAAAAAAiYcFjK3EuBtuEw3lDcvpYAIBM4ww_JtTZ18ewj30Y0Ca4f5RV-HyCk0wj1_tl-mUmHpAEDAzkBACBZAQCo9GhWUyex7JKeFuTHnPVMWwDbMDS9AwO07NeBvgrt-k1M1DXmsPFqbIdUKEdASOLKjeLP5dzjFqVd5aOz9ZixlfomMlYeJr_JYknNPAJ0qWvboQwMnbPktgqYRPMjNvS-FkBuN9LMyV5I8W195O14XyFQ5KuNz09T8P4hvZBR5UGVc6z_O48HHG6P8M1qTUVM21iHOzRkVNj_QHd6Jv51-lDWzzjKCdhmWWfYdoN6lvq3HyKQIFn13P4DjXhhz0qIyrB-9DkASWXu308KERGiqZsxerkpnRGzTzs4Cq8XevShCa3s5_1xtxtvxP2kvFvBuLnf1dEGxv48RpHn6SIBIUMBAAE",
          "clientDataJSON": "eyJjaGFsbGVuZ2UiOiJCakFxejI5RWNfdkp0VW9sYXZuU0FHQWdKY2FVd1RJVnJLSDE2TFhjWUFVIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly93ZWJhdXRobi5maXJzdHllYXIuaWQuYXUiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIn0"
        },
        "type": "public-key"
      }
    }
  },
  "indirect_attest_1": {
    "Passed": {
      "rs": {
        "cred_id": "olVLUBLIsDmwCvQf3v5s53TqOS7teRGtbqt9Uoq3xzI",
        "uv": true,
        "alg": "RS256"
      },
      "ccr": {
        "publicKey": {
          "rp": {
            "name": "webauthn.firstyear.id.au",
            "id": "webauthn.firstyear.id.au"
          },
          "user": {
            "id": "Y29tcGF0dXNlcg",
            "name": "compatuser",
            "displayName": "compatuser"
          },
          "challenge": "XYK1QETOh_FCKxUhKYr0cLzSKQfHa1o2dqlI0BtQlqM",
          "pubKeyCredParams": [
            {
              "type": "public-key",
              "alg": -7
            },
            {
              "type": "public-key",
              "alg": -35
            },
            {
              "type": "public-key",
              "alg": -36
            },
            {
              "type": "public-key",
              "alg": -257
            },
            {
              "type": "public-key",
              "alg": -258
            },
            {
              "type": "public-key",
              "alg": -259
            },
            {
              "type": "public-key",
              "alg": -37
            },
            {
              "type": "public-key",
              "alg": -38
            },
            {
              "type": "public-key",
              "alg": -39
            },
            {
              "type": "public-key",
              "alg": -8
            },
            {
              "type": "public-key",
              "alg": -65535
            }
          ],
          "timeout": 60000,
          "attestation": "indirect",
          "authenticatorSelection": {
            "requireResidentKey": false,
            "userVerification": "discouraged"
          }
        }
      },
      "rpkc": {
        "id": "olVLUBLIsDmwCvQf3v5s53TqOS7teRGtbqt9Uoq3xzI",
        "rawId": "olVLUBLIsDmwCvQf3v5s53TqOS7teRGtbqt9Uoq3xzI",
        "response": {
          "attestationObject": "o2NmbXRmcGFja2VkZ2F0dFN0bXSiY2FsZzkBAGNzaWdZAQBTrKkKEnB7KHhNRoUxEpb5s1fy6ygb3agozdWiBCNYcf1O6uCbp0rh6eScNgZ5ol3rYhp9KNllDkU50pfRUGiemlxnL0kaUfkMkm-P5DQzA4RtZCkISIHnWsOGdzWSQQNQ8-nsjr7po02gJtL0fLrPd9Gyi-5v7Ks73D5n38akU9-1Cv8l6zgMptm0tfvRM6_GF1uBGkkXDCmedye7CITteo7odwltQD_8HLjtno8n9MxOmKb3s6g7oT5c8YrkJVP7siR11CLt08UywZQN75VcvCn_Kj8q51T4o6M9KPVAm13BfxxamPy26wTQErn3NjnTAFTb2Axd-42iHp60xYWEaGF1dGhEYXRhWQFnarm78N-aFvkduzO7sTL6-dF8eCxIJsbscOzuWNl-9SpFAAAAAAiYcFjK3EuBtuEw3lDcvpYAIKJVS1ASyLA5sAr0H97-bOd06jku7XkRrW6rfVKKt8cypAEDAzkBACBZAQCjejzCxfZmoACsb-cdF98bO791UAB4l6hlB3PH82-HVi0yA1UfsGYcOgT2m-tlvZ2drpA319w6roxM-ud5PZcFVKrYWhpBf02Q4kVe4AEF5oxWZlLOYffv1HMr0JK_Qb38LdYPUn1ceFyj8jNnq9C0Y38u-brySirHGEAbOmkaWZjtY9DhCwp2PC0SYl5ZkEP-cFtEVxbEjuiw9kA68ZyOmef_EITkTU4KMQ1WNE0q4TxSUTOVXYE9pw3fBWXyfR7mwuXlRlJfPNCeZySuwX4T41mjtvnXBjAvfuuIQ4sDnA_WeEtEXoWKgpxCDZrLe3w8sjci0wPGIY6Qai6a-YEJIUMBAAE",
          "clientDataJSON": "eyJjaGFsbGVuZ2UiOiJYWUsxUUVUT2hfRkNLeFVoS1lyMGNMelNLUWZIYTFvMmRxbEkwQnRRbHFNIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly93ZWJhdXRobi5maXJzdHllYXIuaWQuYXUiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIn0"
        },
        "type": "public-key"
      }
    }
  },
  "none_attest_1": {
    "Failed": {
      "err": "ParseNOMFailure",
      "ccr": {
        "publicKey": {
          "rp": {
            "name": "webauthn.firstyear.id.au",
            "id": "webauthn.firstyear.id.au"
          },
          "user": {
            "id": "Y29tcGF0dXNlcg",
            "name": "compatuser",
            "displayName": "compatuser"
          },
          "challenge": "FKVseWmr5DxQ_H9iTyoTgRPIClLspXO0XbOKQfMuaFc",
          "pubKeyCredParams": [
            {
              "type": "public-key",
              "alg": -7
            },
            {
              "type": "public-key",
              "alg": -35
            },
            {
              "type": "public-key",
              "alg": -36
            },
            {
              "type": "public-key",
              "alg": -257
            },
            {
              "type": "public-key",
              "alg": -258
            },
            {
              "type": "public-key",
              "alg": -259
            },
            {
              "type": "public-key",
              "alg": -37
            },
            {
              "type": "public-key",
              "alg": -38
            },
            {
              "type": "public-key",
              "alg": -39
            },
            {
              "type": "public-key",
              "alg": -8
            },
            {
              "type": "public-key",
              "alg": -65535
            }
          ],
          "timeout": 60000,
          "attestation": "none",
          "authenticatorSelection": {
            "requireResidentKey": false,
            "userVerification": "discouraged"
          }
        }
      },
      "rpkc": {
        "id": "6h7wVk2n4Buulhd5fiShGb0BBViIgvDoVO3xhn0A0Mg",
        "rawId": "6h7wVk2n4Buulhd5fiShGb0BBViIgvDoVO3xhn0A0Mg",
        "response": {
          "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVkBWGq5u_Dfmhb5Hbszu7Ey-vnRfHgsSCbG7HDs7ljZfvUqRQAAAAAAACDqHvBWTafgG66WF3l-JKEZvQEFWIiC8OhU7fGGfQDQyKQBAwM5AQAgWQEAt86lR2w_hmnhDr6tvJD5hmIuWt0QkG1sphC8aqeOHuIWnbcBWnxNUrKQibJxEGJilM20s-_w-aUjDoV5MYu4NBgguFHju-qA-qe1sjhqY7UkMkx4Z1KGMeiZNNGgk5Gtmu0xjaq-1RohB3TKADeWTularHWzG6q6sJHgC-qKKa67Rmwr0T4a4S3VjLvjvSPILx88nLJvwqO1rDb5cLOgL5CEjtRijR6SNeN05uBhz2ePn5mMo2lN73pHsMGPo68pGWIWWsb2sC_aBF2eA02Me2jldIgSzMy3y8xsTIg6r_xF105pC8jOPsQVN2TJDxN9zVEuxpY_mUsqGOAFGR-SiyFDAQAB",
          "clientDataJSON": "eyJjaGFsbGVuZ2UiOiJGS1ZzZVdtcjVEeFFfSDlpVHlvVGdSUElDbExzcFhPMFhiT0tRZk11YUZjIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly93ZWJhdXRobi5maXJzdHllYXIuaWQuYXUiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIn0"
        },
        "type": "public-key"
      }
    }
  },
  "authdiscouraged": "FailedPrerequisite",
  "authdiscouraged_consistent": "FailedPrerequisite",
  "none_attest_2": {
    "Failed": {
      "err": "ParseNOMFailure",
      "ccr": {
        "publicKey": {
          "rp": {
            "name": "webauthn.firstyear.id.au",
            "id": "webauthn.firstyear.id.au"
          },
          "user": {
            "id": "Y29tcGF0dXNlcg",
            "name": "compatuser",
            "displayName": "compatuser"
          },
          "challenge": "Ykr70oCHYaW3heAsQHfeUQ5ittysUSb6aQL35ah90zA",
          "pubKeyCredParams": [
            {
              "type": "public-key",
              "alg": -7
            },
            {
              "type": "public-key",
              "alg": -35
            },
            {
              "type": "public-key",
              "alg": -36
            },
            {
              "type": "public-key",
              "alg": -257
            },
            {
              "type": "public-key",
              "alg": -258
            },
            {
              "type": "public-key",
              "alg": -259
            },
            {
              "type": "public-key",
              "alg": -37
            },
            {
              "type": "public-key",
              "alg": -38
            },
            {
              "type": "public-key",
              "alg": -39
            },
            {
              "type": "public-key",
              "alg": -8
            },
            {
              "type": "public-key",
              "alg": -65535
            }
          ],
          "timeout": 60000,
          "attestation": "none",
          "authenticatorSelection": {
            "requireResidentKey": false,
            "userVerification": "discouraged"
          }
        }
      },
      "rpkc": {
        "id": "ERVIVbSJuZcS_ewnP1K5rsHuOzJlc8_WJfVijJp8ayw",
        "rawId": "ERVIVbSJuZcS_ewnP1K5rsHuOzJlc8_WJfVijJp8ayw",
        "response": {
          "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVkBWGq5u_Dfmhb5Hbszu7Ey-vnRfHgsSCbG7HDs7ljZfvUqRQAAAAAAACARFUhVtIm5lxL97Cc_Urmuwe47MmVzz9Yl9WKMmnxrLKQBAwM5AQAgWQEA48xXOWz0nxYFasxR2F2b8eOJpS0fRS9F9jDCEZ1NiK8VPUZbqaPDm6mryK9X-3XpNpRkZhNs6rmsZhLAqH9PQneZCuLt9CiNyjD8C1xO9tzFn0iIpuSlzDdRclFAK61pAgnXw_gjYNYpdof71O3bdLuU7X8fGNd42iVjv2hNcB83BXJ2Qe01Vi43_PTtDhg2V2pN7gsLQulJKGc10NgusuPXjdnrTqJOSy9O4tvLqu6XT2AndZJ9xN3ks0YXmcfoA3RLOeYZCWzLd3ayX6Bbk_Ok7V9vMvOuU43tB_fYKaLB8hv1z_-bhlrFpwH4H2gF66KA3WAwysCoLiInVMhucSFDAQAB",
          "clientDataJSON": "eyJjaGFsbGVuZ2UiOiJZa3I3MG9DSFlhVzNoZUFzUUhmZVVRNWl0dHlzVVNiNmFRTDM1YWg5MHpBIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly93ZWJhdXRobi5maXJzdHllYXIuaWQuYXUiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIn0"
        },
        "type": "public-key"
      }
    }
  },
  "authmultiple": "FailedPrerequisite",
  "fallback_alg": "NotTested",
  "uvpreferred": {
    "Failed": {
      "err": "ParseNOMFailure",
      "ccr": {
        "publicKey": {
          "rp": {
            "name": "webauthn.firstyear.id.au",
            "id": "webauthn.firstyear.id.au"
          },
          "user": {
            "id": "Y29tcGF0dXNlcg",
            "name": "compatuser",
            "displayName": "compatuser"
          },
          "challenge": "BZdJ3kGUVbZCiSmYBZXfxWqSrH241ZKnysN_jG-ZSw0",
          "pubKeyCredParams": [
            {
              "type": "public-key",
              "alg": -7
            },
            {
              "type": "public-key",
              "alg": -35
            },
            {
              "type": "public-key",
              "alg": -36
            },
            {
              "type": "public-key",
              "alg": -257
            },
            {
              "type": "public-key",
              "alg": -258
            },
            {
              "type": "public-key",
              "alg": -259
            },
            {
              "type": "public-key",
              "alg": -37
            },
            {
              "type": "public-key",
              "alg": -38
            },
            {
              "type": "public-key",
              "alg": -39
            },
            {
              "type": "public-key",
              "alg": -8
            },
            {
              "type": "public-key",
              "alg": -65535
            }
          ],
          "timeout": 60000,
          "attestation": "none",
          "authenticatorSelection": {
            "requireResidentKey": false,
            "userVerification": "preferred"
          }
        }
      },
      "rpkc": {
        "id": "S8YjipouhTSMTeD5R0DgSssj_KS3tQ0vg-PrKZe0SUU",
        "rawId": "S8YjipouhTSMTeD5R0DgSssj_KS3tQ0vg-PrKZe0SUU",
        "response": {
          "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVkBWGq5u_Dfmhb5Hbszu7Ey-vnRfHgsSCbG7HDs7ljZfvUqRQAAAAAAACBLxiOKmi6FNIxN4PlHQOBKyyP8pLe1DS-D4-spl7RJRaQBAwM5AQAgWQEAt7LzACPAeQa5-UU2oitnIXh3NVUDpmVPQlCgDt9T-roXH6oQK1dHDrB_kcJp6I77BQcRd5Lx-Qhb9g0osrdF--zemBIPScbvjwmiYTyEmycvvhO9NZ8lUB3DFaVd3N3HaEvYXceimFyNVxbt8vwDyYiAU6ZyPF-YfvUGv6Nxe0q0BPSEJLnKvMtX8nyWGEPwEVukimZzAApmhhDvIUm2EvxLXGSbA_8owU4W5iDegErkRd8twI4AaqCxtVKNszPkmHpMZDjMkFyYXQmiIcmYU6EUW60yGr_BbEkPXIgLL19jTWWYcgrLVcdYvoTqeKeLdIixPFM1Ck3zJ24als2_iyFDAQAB",
          "clientDataJSON": "eyJjaGFsbGVuZ2UiOiJCWmRKM2tHVVZiWkNpU21ZQlpYZnhXcVNySDI0MVpLbnlzTl9qRy1aU3cwIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly93ZWJhdXRobi5maXJzdHllYXIuaWQuYXUiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIn0"
        },
        "type": "public-key"
      }
    }
  },
  "authpreferred": "FailedPrerequisite",
  "authpreferred_consistent": "FailedPrerequisite",
  "uvrequired": {
    "Failed": {
      "err": "ParseNOMFailure",
      "ccr": {
        "publicKey": {
          "rp": {
            "name": "webauthn.firstyear.id.au",
            "id": "webauthn.firstyear.id.au"
          },
          "user": {
            "id": "Y29tcGF0dXNlcg",
            "name": "compatuser",
            "displayName": "compatuser"
          },
          "challenge": "gAu9I4xf3y_c1tKasOlDlBKX8gzpHLhoy5FesHl7mv0",
          "pubKeyCredParams": [
            {
              "type": "public-key",
              "alg": -7
            },
            {
              "type": "public-key",
              "alg": -35
            },
            {
              "type": "public-key",
              "alg": -36
            },
            {
              "type": "public-key",
              "alg": -257
            },
            {
              "type": "public-key",
              "alg": -258
            },
            {
              "type": "public-key",
              "alg": -259
            },
            {
              "type": "public-key",
              "alg": -37
            },
            {
              "type": "public-key",
              "alg": -38
            },
            {
              "type": "public-key",
              "alg": -39
            },
            {
              "type": "public-key",
              "alg": -8
            },
            {
              "type": "public-key",
              "alg": -65535
            }
          ],
          "timeout": 60000,
          "attestation": "none",
          "authenticatorSelection": {
            "requireResidentKey": false,
            "userVerification": "required"
          }
        }
      },
      "rpkc": {
        "id": "wBQcWbgrp0xhzOwbTSrxqP3BW3DmZX3mAyUBSxm-xgA",
        "rawId": "wBQcWbgrp0xhzOwbTSrxqP3BW3DmZX3mAyUBSxm-xgA",
        "response": {
          "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVkBWGq5u_Dfmhb5Hbszu7Ey-vnRfHgsSCbG7HDs7ljZfvUqRQAAAAAAACDAFBxZuCunTGHM7BtNKvGo_cFbcOZlfeYDJQFLGb7GAKQBAwM5AQAgWQEAvdQhpHWoxeJ6uQu5WhxgGC6PzZ2AOsO3eMjDOwvlHQ1sidxYyN0WV-Ck9JPyUx9DXyv5b4tEVxVo9dlMYfmmUC2s58ZAc-6UXzHGOsT3EqpiPxJxun5qfV_8fOtAFoLHp67NS_xc1tfwZW1kXPqkZNG0d-l-M_E1kAohajZwQdZflAqgVXBLrJPJ5D7TPiFdibVaFQJMpGIciWRmzCjM-NEG7kvKjQUDd3Z6Evm9lUDlUVUzDvdbQ1I2VfkY_3ufbCemBkbsL3tt_OMahNUI-9FCwpx_f29CcAsK2m2TYm8oYT69tPPpTMyVMTEppDaVC54hIn6OsVr5FIK4FBWXeSFDAQAB",
          "clientDataJSON": "eyJjaGFsbGVuZ2UiOiJnQXU5STR4ZjN5X2MxdEthc09sRGxCS1g4Z3pwSExob3k1RmVzSGw3bXYwIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly93ZWJhdXRobi5maXJzdHllYXIuaWQuYXUiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIn0"
        },
        "type": "public-key"
      }
    }
  },
  "authrequired": "FailedPrerequisite"
}
```

**Comment by Firstyear** [comment] 2022-03-14 01:02
Thanks @ericmarkmartin ! Want me to leave it to you to implement these changes? Or do you want me to take a look? (PS: How useful is that compat tester hey!)

**Comment by ericmarkmartin** [comment] 2022-03-24 04:49
This issue is due to the authenticator only emitting 1 null byte to indicate an aaguid of 0. [The spec][1] specifies that the aaguid should be 16 bytes.

[1]: https://www.w3.org/TR/webauthn-2/#sctn-attested-credential-data

**Comment by Firstyear** [comment] 2022-03-24 22:30
Since #109 documents this, I'll close this. Thanks so much @ericmarkmartin for your great detective work!

**Comment by Firstyear** [comment] 2022-03-30 00:06
@akshayku

**Comment by akshayku** [comment] 2022-03-31 15:27
I tried to reproduce this with above create settings but couldn't repro. Can you file a feedback hub bug on this and share the id?

**Comment by aseigler** [comment] 2022-03-31 18:08
I can repro...but only specifically with Firefox 98.  Previous Firefox did not fail, Edge works just fine as well.

Here's what comes out of the authenticator (via `Microsoft-Windows-WebAuthN/Operational` log):

```
{"deviceInfo": {"maxMsgSize": 0, "maxSerializedLargeBlobArray": 0, "providerType": "Platform", "providerName": "MicrosoftPlatformProvider", "residentKey": true}, "status": 0, "response": h'00A301646E6F6E65025901676AB9BBF0DF9A16F91DBB33BBB132FAF9D17C782C4826C6EC70ECEE58D97EF52A4500000000000000000000000000000000000000000020041DCEDF292AE4F1B697EF1A92CF015D70B438C6597784EB39BAF9D4D6C9C43BA401030339010020590100E53DA6B8309F5A8031C99A83429BB48B75F99868B09FFE7F5702B80E071071B2961AB990A340F70F24AD4252E9C9E93F232EC493914F4C152D722E200D0704CB345EC46E2F265D799DDE31BBD6D7B77053881025EF3681A4E913B8B3F9B9FA4C3B4A394DEC7F633CF9BE58D7D681F0B320556AB6A3ED283604F6A630E759BA56B97673358950289955DA54321D6F60B4CA6894E082689BA322B0F7550F43E20192114FECCEE557019AE030976846F6E53A2556343AADC09A3C0B391AAA73273FBA2DB50979F2E3697BF22969D3691F5C57F4A0165980EFBBB58F45BCCC485B94CD48417004CC8189BEDE554657BF7CCAA3DC22A42A3529B19321529C5EE53D25214301000103A0'}
```
The inner response:
```
{1: "none", 2: h'6AB9BBF0DF9A16F91DBB33BBB132FAF9D17C782C4826C6EC70ECEE58D97EF52A4500000000000000000000000000000000000000000020041DCEDF292AE4F1B697EF1A92CF015D70B438C6597784EB39BAF9D4D6C9C43BA401030339010020590100E53DA6B8309F5A8031C99A83429BB48B75F99868B09FFE7F5702B80E071071B2961AB990A340F70F24AD4252E9C9E93F232EC493914F4C152D722E200D0704CB345EC46E2F265D799DDE31BBD6D7B77053881025EF3681A4E913B8B3F9B9FA4C3B4A394DEC7F633CF9BE58D7D681F0B320556AB6A3ED283604F6A630E759BA56B97673358950289955DA54321D6F60B4CA6894E082689BA322B0F7550F43E20192114FECCEE557019AE030976846F6E53A2556343AADC09A3C0B391AAA73273FBA2DB50979F2E3697BF22969D3691F5C57F4A0165980EFBBB58F45BCCC485B94CD48417004CC8189BEDE554657BF7CCAA3DC22A42A3529B19321529C5EE53D252143010001', 3: {}}
```
Notice all those zeroes in a row there, that's the AAGUID.  This is what Firefox is sending:
```
{
  "id": "BB3O3ykq5PG2l-8aks8BXXC0OMZZd4TrObr51NbJxDs",
  "rawId": "BB3O3ykq5PG2l-8aks8BXXC0OMZZd4TrObr51NbJxDs",
  "response": {
    "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVkBWGq5u_Dfmhb5Hbszu7Ey-vnRfHgsSCbG7HDs7ljZfvUqRQAAAAAAACAEHc7fKSrk8baX7xqSzwFdcLQ4xll3hOs5uvnU1snEO6QBAwM5AQAgWQEA5T2muDCfWoAxyZqDQpu0i3X5mGiwn_5_VwK4DgcQcbKWGrmQo0D3DyStQlLpyek_Iy7Ek5FPTBUtci4gDQcEyzRexG4vJl15nd4xu9bXt3BTiBAl7zaBpOkTuLP5ufpMO0o5Tex_Yzz5vljX1oHwsyBVaraj7Sg2BPamMOdZula5dnM1iVAomVXaVDIdb2C0ymiU4IJom6MisPdVD0PiAZIRT-zO5VcBmuAwl2hG9uU6JVY0Oq3AmjwLORqqcyc_ui21CXny42l78ilp02kfXFf0oBZZgO-7tY9FvMxIW5TNSEFwBMyBib7eVUZXv3zKo9wipCo1KbGTIVKcXuU9JSFDAQAB",
    "clientDataJSON": "eyJjaGFsbGVuZ2UiOiJONHdyRG9ycnlvbUdjdWFycjU1bDkwaWlsaGZOZElyTTVyejZDeHNnYmtJIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly93ZWJhdXRobi5maXJzdHllYXIuaWQuYXUiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIn0"
  },
  "type": "public-key"
}
```
Here's the attestation object, base64 and CBOR decoded:
```
{"fmt": "none", "attStmt": {}, "authData": h'6AB9BBF0DF9A16F91DBB33BBB132FAF9D17C782C4826C6EC70ECEE58D97EF52A4500000000000020041DCEDF292AE4F1B697EF1A92CF015D70B438C6597784EB39BAF9D4D6C9C43BA401030339010020590100E53DA6B8309F5A8031C99A83429BB48B75F99868B09FFE7F5702B80E071071B2961AB990A340F70F24AD4252E9C9E93F232EC493914F4C152D722E200D0704CB345EC46E2F265D799DDE31BBD6D7B77053881025EF3681A4E913B8B3F9B9FA4C3B4A394DEC7F633CF9BE58D7D681F0B320556AB6A3ED283604F6A630E759BA56B97673358950289955DA54321D6F60B4CA6894E082689BA322B0F7550F43E20192114FECCEE557019AE030976846F6E53A2556343AADC09A3C0B391AAA73273FBA2DB50979F2E3697BF22969D3691F5C57F4A0165980EFBBB58F45BCCC485B94CD48417004CC8189BEDE554657BF7CCAA3DC22A42A3529B19321529C5EE53D252143010001'}
```
If you look at the inner response above vs the authData they start out the same until you get to the aaguid, then you lose a bunch of them, corrupting the object.  Again, only on Firefox 98.

**Comment by Firstyear** [comment] 2022-03-31 22:23
Right, so that means it's a firefox bug then. @msirringhaus What do you think? Is this something you could help with?

**Comment by msirringhaus** [comment] 2022-04-01 07:07
Yes, this was a bug in FF and it has been fixed a few days ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1759098

**Comment by ericmarkmartin** [comment] 2022-04-02 00:19
Just tested on Firefox Nightly (100.0a1) and can confirm it works

**Comment by Firstyear** [comment] 2022-04-02 01:50
Thank you all for your input! It's much appreciated :)

**Closed by Firstyear** 2022-04-02 01:50 UTC

**Comment by devsnek** [comment] 2022-04-03 06:46
i'm not really sure what this means but i just observed the warning in chromium 99 on linux. it also says the challenge failed.

**Comment by Firstyear** [comment] 2022-04-03 23:26
@devsnek Can you please run https://webauthn.firstyear.id.au/compat_test and submit a seperate bug report so that we can investigate?

**Comment by ericmarkmartin** [comment] 2022-04-03 23:51
> i'm not really sure what this means but i just observed the warning in chromium 99 on linux.

If you're saying that you're seeing the warning in the console logs when running the compat test locally, then I'm not super surprised. Here's the snippet of code producing that warning.
```rust
if let Some(0) = i.first() {                                                 
    warn!(                                                                   
        "Aaguids beginning with 0 are suspicious. This could be the Firefox \
         98 Windows bug where a zero aaguid gets truncated down to 1 byte."  
    );                                                                       
}
```
If your browser is using 16 zeroes as the aaguid, then our check will fire. @Firstyear, maybe what we actually want to do is if the first byte of the aaguid is zero _and_ the aaguid is non-zero, we warn, e.g.
```rust
let (i, aaguid) = take(16usize)(i)?;                                          
let aaguid = aaguid.try_into().expect("took 16 bytes exactly");               
// `aaguid` is actually big endian, but it doesn't matter here because we're  
// just checking if it's non-zero, and we expect `from_ne_bytes` to be faster.
if i[0] == 0u8 && u128::from_ne_bytes(aaguid) != 0u128 {                      
    warn!(                                                                    
        "Aaguids beginning with 0 are suspicious. This could be the Firefox \ 
         98 Windows bug where a zero aaguid gets truncated down to 1 byte."   
    );                                                                        
}                                                                             
```

**Comment by Firstyear** [comment] 2022-04-03 23:55
Well, they also mentioned that the challenge failed, so that is a seperate issue to this I would think. But yes, I think that check is possibly better. We could also consider just removing that warning soon or making it trace!() only since it's resolved in FF now ....

Alternately, a different way to warn on it could be to check the cred_id_len we got is <= i.len(), because if it's larger then we know that something is going side ways. Then we check inside that if the first byte of the aaguid is 0. What do you think about that?

**Comment by ericmarkmartin** [comment] 2022-04-04 01:54
> Alternately, a different way to warn on it could be to check the cred_id_len we got is <= i.len(), because if it's larger then we know that something is going side ways. Then we check inside that if the first byte of the aaguid is 0. What do you think about that?

This check does also seem good, though I think deleting it probably makes more sense. Given that the bug is isolated to FF 98 and we've documented that in the README and as soon as 99 is released we should probably expect few people to be on 98.

**Comment by aseigler** [comment] 2022-04-04 02:12
Even simpler, if the object doesn't end up a complete CBOR map with only expected components and with no extra garbage, it fails.  That's how the conformance tests are written.

**Comment by Firstyear** [comment] 2022-04-04 02:36
> Even simpler, if the object doesn't end up a complete CBOR map with only expected components and with no extra garbage, it fails. That's how the conformance tests are written.

We already have that, and that's what triggered the failure here. This is about helping us to see *why* that specific failure is occuring.

**Comment by Firstyear** [comment] 2022-04-04 02:36
> > Alternately, a different way to warn on it could be to check the cred_id_len we got is <= i.len(), because if it's larger then we know that something is going side ways. Then we check inside that if the first byte of the aaguid is 0. What do you think about that?
> 
> This check does also seem good, though I think deleting it probably makes more sense. Given that the bug is isolated to FF 98 and we've documented that in the README and as soon as 99 is released we should probably expect few people to be on 98.

I think we should add the length check anyway, because it certainly hints at something invalid.

**Comment by devsnek** [comment] 2022-04-04 14:58
i don't see any issues in the compat test. i guess i should mention i'm testing with a yubikey 5c nfc. in the code i'm working on i see `Aaguids beginning with 0 are suspicious ...` followed by `WebAuthn protocol error. MismatchedChallenge`. i'm assuming these are due to me encoding something wrong somewhere between my rust, protobuf, python, and browser code, and not this library. i can still open a separate issue if you'd like though.

**Comment by ericmarkmartin** [comment] 2022-04-04 15:39
> i guess i should mention i'm testing with a yubikey 5c nfc.

I also use a 5c NFC and haven't encountered this.

> in the code i'm working on i see `Aaguids beginning with 0 are suspicious ...`

I'm going to try to land the change to less eagerly warn this sort of thing (as discussed above) soon. In the meantime, you can try logging the Aaguid---if it's all zero, then it's probably safe to ignore this warning. Otherwise, I think it merits investigation.

> i'm assuming these are due to me encoding something wrong somewhere between my rust, protobuf, python, and browser code, and not this library.

Given you're not seeing issues in the compat test, then this seems likely.

> i can still open a separate issue if you'd like though.

I defer to @Firstyear as to the correct course of action.

**Comment by Firstyear** [comment] 2022-04-04 22:34
@devsnek Can you open a new issue so we can talk about your specific environment and your issues there rather than on this issue please?
